# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 500000

runner: "parallel"
batch_size_run: 8
training_iters: 8

entity_last_action: True # Include the user-controlled agents' last actions (one_hot) in their entities

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "msg_q_learner"
double_q: True
mixer: "flex_qmix"
mixing_embed_dim: 32
hypernet_embed: 128
softmax_mixing_weights: True
agent: "comm_imagine_entity_attend_rnn"
rnn_hidden_dim: 64
mac: "rlcomm_mac"
attn_embed_dim: 128
attn_n_heads: 4
lmbda: 0.5

# elector_agent setting
elect_attn_embed_dim: 128
elect_hidden_dim: 32

name: "rlsocom"

# Specificed Params
use_msg: True
header_num: 2
msg_dim: 3
msg_T: 4
msg_entropy_weight: 0.01
msg_ce_weight: 0.01
random_master: True
ceb_weight: 0.01
ceb_kl_weight: 0.01
generation_alpha: 1.0
no_summary: False
no_feedback: False
order_leader: False
select_by_prob: False
run: "sog"

# communication type
only_use_head_msg: 1
